### ISSUE TITLE
Question about x0

### ISSUE THREAD

**Issue by SHITIANYU-hue** [YaChienChang/Neural-Lyapunov-Control#3]
The x0 in the paper should be the stable point, or target point, why in the code it is:
x_0 = torch.zeros([1, 2])?

**Comment by YaChienChang** [comment]
Hi, 
The origin is the stable point in all examples of the paper, so x_0 = torch.zeros([1, 2]). 
For applying this method to other examples, you can transform the stable point to the origin for learning Lyapunov functions.
